entity/ShopifyEntities.xml
service/co/hotwax/shopify/fulfillment/ShopifyFulfillmentServices.xml
service/co/hotwax/shopify/system/ShopifySystemMessageServices.xml

1) Overridden queue#SystemMessage service to allow for synchronous send.
2) Extended SystemMessage entity to store orderId reference.

Override queue#SystemMessage and extended SystemMessage entity

---

data/ShopifySetupSeedData.xml
data/UpgradeData_Upcoming.xml

1. Did some improvements in the data.
2. Improved the shopify directory name for consistency.
3. Added parent type id in upgrade data where it wasn't present.

Improved: Refactored shopify directory name for consistency

---

component.xml
data/UpgradeData_v2.0.0.xml

closes #30 
1. Updated version in the component.xml file for the upcoming release.

Updated: version in the component.xml file for the upcoming release

---

data/UpgradeData_v1.2.0.xml
upgrade/upcoming/UpgradeSteps.md

1. Added upgrade steps for upcoming release.

Added: Upgrade steps for upcoming release for OMS Fulfillment Feed

---

upgrade/upcoming/UpgradeSteps.md

1. Added upgrade steps for the upcoming release.

Added: Upgrade steps for OMS Synced Refunds Feed and improved for OMS fulfillment Feed

---

upgrade/upcoming/UpgradeSteps.md
upgrade/v1.3.2/UpgradeSteps.md

Added the upgrade steps to be followed for setting up the OMSOrderIdsFeed service job for fetching order meta fields from Shopify

Added: Upgrade Steps related to OMSOrderIdsFeed service

---

service/co/hotwax/shopify/system/ShopifySystemMessageServices.xml

PR to change to return statement with type warning, in case there is no shipments.

Improved: Added return statement with warning type if there is no shipments

---

upgrade/v1.3.2/UpgradeSteps.md

Added the SendBulkCreateGiftCardsResult system message type id in the upgrade steps.

Improved: Updated the upgrade steps for v1.3.2

---

upgrade/v1.3.1/UpgradeSteps.md
upgrade/v1.3.2/UpgradeSteps.md

Added upgrade steps file related to gift card activation

Added: Upgrade steps for the version 1.3.1

---

data/ShopifySetupSeedData.xml
data/UpgradeData_Upcoming.xml
service/co/hotwax/shopify/system/ShopifySystemMessageServices.xml
upgrade/upcoming/UpgradeSteps.md

Added dateTime precision up to milliseconds & systemMessageId in the GenerateOrderMetafieldsFeed systemMessageType's sendPath

Improved: Added dateTime precision up to milliseconds 

---

data/ShopifyTemplateData.xml
data/UpgradeData_Upcoming.xml
service/co/hotwax/shopify/order/ShopifyOrderServices.xml
service/shopify.rest.xml

This is required as part of Shopify Fulfilment Error Report enhancements.

Added: A new API and service to get order details from Shopify

---

data/ShopifyServiceJobData.xml
data/UpgradeData_Upcoming.xml
upgrade/Upcoming/UpgradeSQL.sql
upgrade/Upcoming/UpgradeSteps.md

Added Enumerations and EnumerationTypes for ServiceJobs

Added Enumerations and EnumerationTypes for ServiceJobs

---

data/ShopifyServiceJobData.xml
data/UpgradeData_Upcoming.xml

Added enumCode to Enumeration Data

Added enumCode to Enumeration Data

---

data/ShopifyServiceJobData.xml
data/ShopifySetupSeedData.xml
data/ShopifyTemplateData.xml
data/UpgradeData_Upcoming.xml
service/co/hotwax/shopify/system/ShopifySystemMessageServices.xml

- Fetching fulfillment_orders from using Bulk GraphQL query.
- Sending data to SFTP.
- Polling data and allocating orders to the assigned locations.
Related Issue: [#1188](https://git.hotwax.co/HC2/plugins/ofbiz-oms-usl/-/issues/1188)

Implemented flow to get fulfillment_orders from Shopify

---

data/ShopifyServiceJobData.xml
data/ShopifySetupSeedData.xml
data/ShopifyTemplateData.xml
data/UpgradeData_Upcoming.xml

Added system message types, job and template date for getting product metafields by tags for the given namespace.
closes: [#1189](https://git.hotwax.co/HC2/plugins/ofbiz-oms-usl/-/issues/1189)

Added support to get Product data using bulk query 

---

data/ShopifyServiceJobData.xml
data/ShopifySetupSeedData.xml
data/ShopifyTemplateData.xml
data/UpgradeData_Upcoming.xml
service/co/hotwax/shopify/product/ShopifyProductServices.xml

(Mistakenly added ShopifyProductServices.xml, but it's no harm.)

Changed systemMessageTypeId and references to make it < 40 chars.

---

data/ShopifyTemplateData.xml
service/co/hotwax/shopify/return/ShopifyReturnServices.xml

**Referred Document** - https://docs.google.com/document/d/1A94C6JfxDVuI5zfpzPSe5WNeliCaOnOJT7e3LPaaU1I/edit?usp=sharing

Updated the template data to fetch required fields in Exchange V2 Transformation

---

service/co/hotwax/shopify/fulfillment/ShopifyFulfillmentServices.xml
service/co/hotwax/shopify/system/ShopifySystemMessageServices.xml

1. Updated the send#ShopifyFulfillmentSystemMessage to send the shipment map as in from the polled feed file.
2. Updated the generate#ShopifyFulfillmentAckFeed to prepare the map at shipment level and not item level.

Updated the HC to Shopify Fulfillment flow

---

data/ShopifyTemplateData.xml
service/co/hotwax/shopify/fulfillment/ShopifyFulfillmentServices.xml
service/co/hotwax/shopify/return/ShopifyReturnServices.xml
service/co/hotwax/shopify/system/ShopifySystemMessageServices.xml

The added fields help in calculation logic optimization and bypassing certain hardcoded values as well

Updated the GraphQL Queries to fetch additional fields

---

data/ShopifyTemplateData.xml
data/UpgradeData_Upcoming.xml

1. Added vendor in product template in template data file and in upgrade data file as well.

Added: vendor field in product template to apply any custom logic based on vendor if required

---

data/ShopifyTemplateData.xml
data/UpgradeData_Upcoming.xml

Added category in the product graphql query.

Added: category in the ProductByIdQuery graphql template

---

data/ShopifyServiceJobData.xml

@Chinmay2107 can you help me out here too? Seems like you already covered part of this in your MR and I just forgot to make an MR for my changes.

Added product data for jobs

---

data/ShopifyServiceJobData.xml
data/UpgradeData_Upcoming.xml

**Update fromDate and product ID to resolve 'Data too long for column PRODUCT_ID' error**
- Replaced fromDate ${nowTimeStamp} with static value '2025-01-01 00:00:00.0'
- Updated PRODUCT_ID to prevent data truncation error

fix: update fromDate and product ID to resolve 'Data too long for column PRODUCT_ID' error
